spring:
  application:
    name: transportation-service
  datasource:
    url: jdbc:mysql://localhost:3306/transport
    username: root
    password: kyaw
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka
