spring:
  application:
    name: affable-bean-backend-service
  datasource:
    url: jdbc:mysql://localhost:3306/affable_backend
    username: root
    password: kyaw
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka
server:
  port: 0

